name: Publish Merged Packages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  post-merge:
    runs-on: ubuntu-latest
    if: (github.event.action == 'closed' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup git user
        shell: bash
        run: git config user.email "bot@weichwarenprojekt.de" && git config user.name "Weichwarenbot 🚀"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile
      - name: Version
        shell: bash
        run: yarn nx affected --base=${{ github.event.pull_request.base.sha }} --target=version
        # push the changes
      - run: git push --follow-tags
      - name: Publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: npx nx affected --base=${{ github.event.pull_request.base.sha }} --target=publish
